### ISSUE TITLE
You can 'salute' your own builds

### ISSUE THREAD

**Issue by JohannesMP** [drg-tools/karl.gg#197] opened 2021-05-07 22:25 UTC
When viewing your own build you can salute it yourself
![image](https://user-images.githubusercontent.com/662874/117514308-60b65400-af48-11eb-946a-71329abd89c1.png)

This is of course fairly minor since you can only add a single salute, and may even be by design, but it's amusing.

I would have expected the button to be disabled when viewing your own builds.

**Comment by Darthmaul** [comment] 2021-05-07 23:20
Howdy!

Thanks for reporting -- this is working as intended. We have no issues with users being able to salute their own loadouts (similar to Reddit's style of upvotes). 

I'll go ahead and close this as it's not a feature we intend to change at this time. Thanks for the feedback.

**Comment by chaseconey** [comment] 2021-05-07 23:25
@Darthmaul maybe we reopen to default a new build to be upvoted instead of not?

**Comment by Darthmaul** [comment] 2021-05-07 23:29
> 
> 
> @Darthmaul maybe we reopen to default a new build to be upvoted instead of not?

Fine with me, are we okay with not retroactively upvoting existing builds which haven't had this applied?

**Comment by Darthmaul** [comment] 2021-05-17 18:23
We have now implemented the feature where loadouts are upvoted by default -- enjoy.

**Closed by Darthmaul** 2021-05-17 18:23 UTC
Labels: enhancement
